Feat/initial implementation
b0r-r/checker pull request #1
Opened 2024-08-25 17:23 UTC by b0r-r

Added parser + captcha extraction

2024-08-25 21:34 UTC, h5law requested changes
Good start see the comments I made but nice work!

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +	})
You only want the captcha so use your browser console to try identify anything you can use in here to filter out the rest so we dont download all possible images. Here it seems you'll end up downloading every image on the site which could become very annoying.

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +			}
Are you not supposed to handle this error? - If you can't get the captcha you cant move forward so we would want to panic or something similiar here as we will just continue to error later on.

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +	doc.Find("img").Each(func(index int, item *goquery.Selection) {
Should this have an error return?

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +	pageURL := "https://eais.rkn.gov.ru/"
```suggestion

const pageURL = "https://eais.rkn.gov.ru/"

func Parser() {
```

We dont change it and it doesn't change so keep it a global constant incase we need to use it outside the Parser function

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +	out, err := os.Create(filepath.Base(url))
You should specify a name you can refer to later - maybe make a tempdir and just save them there so you can cleanup after you're done with them and use the way you save the name to reference them when needed

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +	defer resp.Body.Close()
Nice 🔥

2024-08-25 21:34 UTC, h5law commented on web/parser.go
> +func Parser() {
```suggestion
func Parser() error {
```

Instead of fmt.Println errors return them instead and you can track them where this will be used

2024-08-27 18:23 UTC, b0r-r commented on web/parser.go
> +	defer resp.Body.Close()
:)

2024-08-27 18:23 UTC, b0r-r commented on web/parser.go
> +func Parser() {
done

2024-08-29 20:10 UTC, closed without merging